blank_issues_enabled: true
contact_links:
  - name: KhmerStack
    url: https://khmerstack.muyleanging.com
    about: Community and project updates.
  - name: Founder Website
    url: https://muyleanging.com
    about: Contact Ing Muyleang.
